ansible_user: root
ansible_ssh_private_key_file: ~/infra/datacenter-bauru/vagrant/ansible-user.key

monitorados:
  servidores:
    - nome: 'ubuntu01'
      url: '10.0.0.101:9100'
    - nome: 'ubuntu02'
      url: '10.0.0.102:9100'
    - nome: 'ubuntu03'
      url: '10.0.0.103:9100'
  sistemas:
    - nome: 'servicedesk'
      url: 'sistemas.fc.unesp.br'
      contexto: '/servicedesk/actuator/prometheus'
