version: "3.8"

services:

  db-postgresql:
    image: postgres:latest
    container_name: postgresql-server
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata_postgresql:/var/lib/postgresql/data

volumes:
  pgdata_postgresql:
