version: "3.8"

services:

  db-servicedesk:
    image: postgres:11.7
    container_name: servicedesk-postgresql
    environment:
      - POSTGRES_DB=servicedesk_v2
      - POSTGRES_USER=servicedesk_v2
      - POSTGRES_PASSWORD=iNgohl6L
    ports:
      - 5432:5432
    volumes:
      - pgdata_servicedesk:/var/lib/postgresql/data

volumes:
  pgdata_servicedesk:
