version: "3.8"

services:

  db-webportaria:
    image: postgres:12.3
    container_name: webportaria-postgresql
    environment:
      - POSTGRES_DB=webportaria
      - POSTGRES_USER=webportaria
      - POSTGRES_PASSWORD=webportaria
    ports:
      - 5432:5432
    volumes:
      - pgdata_webportaria:/var/lib/postgresql/data

volumes:
  pgdata_webportaria:
