- name: Instalar pacotes básicos

  hosts: all

  tasks:
    - name: Update apt-get repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Instalar pacotes básicos Ubuntu
      apt:
        state: latest
        name:
        - ntpdate
        - sendmail
        - apt-show-versions
        - powerline
        - sysvbanner
        - boxes
        - python3-pip
      when: ansible_distribution == 'Ubuntu'

    - name: Instalar módulos python
      pip:
        executable: pip3
        state: latest
        name:
          - jsondiff
          - ansible==2.9.9
          - docker
          - XenAPI
      when: ansible_distribution == 'Ubuntu'

    - name: Instalar pacotes básicos CentOS
      yum:
        state: latest
        name:
        - epel-release
      when: ansible_distribution == 'CentOS'

    - name: Instalar pacotes básicos CentOS
      yum:
        state: latest
        name:
          - logwatch
          - htop
          - sendmail
          - logwatch
          - python3-pip
      when: ansible_distribution == 'CentOS'
